name: Deploy to Staging

on:
  push:
    branches: [develop, staging]
    paths:
      - 'backend/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cybersec-git-expert/request-backend

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push staging image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging

    - name: Deploy to Staging EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 54.144.9.226
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Set variables
          IMAGE_NAME="ghcr.io/cybersec-git-expert/request-backend:staging"
          CONTAINER_NAME="request-backend-staging"
          
          # Login to GitHub Container Registry
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Pull staging image
          docker pull $IMAGE_NAME
          
          # Stop and remove existing staging container
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
          
          # Start staging container on different port
          docker run -d \
            --name $CONTAINER_NAME \
            --restart unless-stopped \
            --env-file /home/ubuntu/staging.env \
            -p 127.0.0.1:3002:3001 \
            $IMAGE_NAME
          
          # Wait for container to start
          sleep 10
          
          # Create uploads symlink
          docker exec $CONTAINER_NAME ln -sf /app/deploy-package/uploads /app/uploads || true
          
          echo "Staging deployment completed"

    - name: Staging Status
      run: |
        echo "✅ Staging deployment successful!"
        echo "🔗 Staging Server: http://54.144.9.226:3002"
